name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: amigo_oculto
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Run tests
      run: pnpm test
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/amigo_oculto
        JWT_SECRET: test-secret-key
        VITE_APP_ID: test-app-id
        OAUTH_SERVER_URL: https://api.manus.im
        VITE_OAUTH_PORTAL_URL: https://portal.manus.im
        OWNER_NAME: Test Owner
        OWNER_OPEN_ID: test-open-id
        BUILT_IN_FORGE_API_URL: https://api.manus.im
        BUILT_IN_FORGE_API_KEY: test-key
        VITE_FRONTEND_FORGE_API_KEY: test-key
        VITE_FRONTEND_FORGE_API_URL: https://api.manus.im
        VITE_ANALYTICS_ENDPOINT: https://analytics.manus.im
        VITE_ANALYTICS_WEBSITE_ID: test-id

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build application
      run: pnpm build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: dist
    
    - name: Deploy to production
      run: |
        echo "Deploy configuration needed"
        echo "Configure your deployment target (Heroku, Railway, Render, etc.)"
      # Adicione suas instruções de deploy aqui
      # Exemplo para Heroku:
      # - name: Deploy to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
